# This is the language of our project.
language: php

services:
 - mysql
 # - postgresql
 # - docker

# Cache NPM's and Composer's caches to speed up build times.
cache:
 directories:
  - $HOME/.composer/cache
  - $HOME/.npm

# Determines which versions of PHP to test our project against.
php:
 - 7.4

# This section sets up the environment variables for the build.
env:
 global:
  # This line determines which version branch of Moodle to test against.
  - MOODLE_BRANCH=MOODLE_39_STABLE
  - IGNORE_PATHS=lang,editor,library,reporting
 # This matrix is used for testing against multiple databases.
 matrix:
  - DB=mysqli
  # - DB=postgresql
  # - DB=docker

# This lists steps that are run before the installation step.
before_install:
 # This disables XDebug which should speed up the build.
 - phpenv config-rm xdebug.ini
 # Currently we are inside of the clone of your repository.  We move up two
 # directories to build the project.
 - cd ../..
 - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
 # Update the $PATH so scripts from this project can be called easily.
 - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

# This lists steps that are run for installation and setup.
install:
 - moodle-plugin-ci install

script:
 # This step makes sure that your plugin
 # conforms to the Moodle coding standards.
 - moodle-plugin-ci validate
 # This step check whether the code conforms to Moodle Code Standards
 - moodle-plugin-ci codechecker
 # This step runs the PHPUnit tests of the plugin.
 - moodle-plugin-ci phpunit
 # This step runs the Behat tests of the plugin.
 # - moodle-plugin-ci behat --profile chrome
